[package]
name = "gmtk22"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agb = { version = "0.9.2", path = "../agb/agb", features = ["freq32768"] }

[profile.dev]
opt-level = 2
debug = true


[profile.release]
panic = "abort"
lto = true
debug = true
