version = "1.0"

[image.descriptions1]
filename = "descriptions1.png"
tile_size = "8x8"
transparent_colour = "121105"

[image.descriptions2]
filename = "descriptions2.png"
tile_size = "8x8"
transparent_colour = "121105"